// AI-assisted: Claude Code (Opus 5.5), 2026-10-08. Scope: generates docs/state-transitions.md. Reviewed by <name>.
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { CREATE, TRANSITIONS, type Action } from '../domain/transitions.js';

const code = (s: string) => `\`${s}\``;
const list = (items: string[]) => (items.length ? items.map(code).join(', ') : '-');

export function renderTransitionsDoc(): string {
  const rows = (Object.keys(TRANSITIONS) as Action[]).map((action) => {
    const t = TRANSITIONS[action];
    return `| ${action} | ${t.from} | ${t.to} | ${t.actors.join(', ')} | ${list(t.where)} | ${list(t.set)} | ${t.credit} | ${code(t.event.routingKey)} | ${t.trigger} |`;
  });
  const create = `| create | - | ${CREATE.to} | ${CREATE.actors.join(', ')} | - | - | ${CREATE.credit} | ${code(CREATE.event.routingKey)} | ${CREATE.trigger} |`;

  return [
    '<!-- Generated by `npm run docs:transitions` from src/domain/transitions.ts. Do not edit by hand. -->',
    '# Order state transitions',
    '',
    '| Action | From | To | Who | Extra conditions | Extra changes | Credit effect | Event | Trigger |',
    '|---|---|---|---|---|---|---|---|---|',
    create,
    ...rows,
    '',
    'Who:',
    '- requester: the caller is the order\'s requester',
    '- runner: the caller is the order\'s assigned runner',
    '- nonRequester: any logged-in user except the requester',
    '- system: a background job',
    '',
    'Every transition is one conditional UPDATE (id + from status + who + extra conditions), plus one',
    '`order_status_history` row and one `outbox_events` row, in one transaction. `version` goes up by 1.',
    '',
    'Any other transition returns 409 `ILLEGAL_TRANSITION`. Confirming an order that is already COMPLETED returns',
    '200 with the current order and changes nothing.',
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const dir = fileURLToPath(new URL('../../docs/', import.meta.url));
  mkdirSync(dir, { recursive: true });
  writeFileSync(`${dir}state-transitions.md`, renderTransitionsDoc());
  console.log(`Wrote ${dir}state-transitions.md`);
}
